// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFz7B_bqVsIDcHIfUcFrhnBX5UlmRtfM',
    appId: '1:241392997335:web:c7a83f420b7888bbfaf192',
    messagingSenderId: '241392997335',
    projectId: 'vibzcheck-1aa90',
    authDomain: 'vibzcheck-1aa90.firebaseapp.com',
    storageBucket: 'vibzcheck-1aa90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcbECe3-aTSzEbBGsqIb8VOEzyXuaPT7I',
    appId: '1:241392997335:android:755a5ae6372b267afaf192',
    messagingSenderId: '241392997335',
    projectId: 'vibzcheck-1aa90',
    storageBucket: 'vibzcheck-1aa90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqDJmbUavxaSMQri-fR-GAi4B2vfjK8uY',
    appId: '1:241392997335:ios:fbdc282b91862d3cfaf192',
    messagingSenderId: '241392997335',
    projectId: 'vibzcheck-1aa90',
    storageBucket: 'vibzcheck-1aa90.firebasestorage.app',
    iosClientId: '241392997335-da1oi9hqqvv0vc8gfpmnfgltsfll7mpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqDJmbUavxaSMQri-fR-GAi4B2vfjK8uY',
    appId: '1:241392997335:ios:fbdc282b91862d3cfaf192',
    messagingSenderId: '241392997335',
    projectId: 'vibzcheck-1aa90',
    storageBucket: 'vibzcheck-1aa90.firebasestorage.app',
    iosClientId: '241392997335-da1oi9hqqvv0vc8gfpmnfgltsfll7mpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnFz7B_bqVsIDcHIfUcFrhnBX5UlmRtfM',
    appId: '1:241392997335:web:89cd96eeadd6e46dfaf192',
    messagingSenderId: '241392997335',
    projectId: 'vibzcheck-1aa90',
    authDomain: 'vibzcheck-1aa90.firebaseapp.com',
    storageBucket: 'vibzcheck-1aa90.firebasestorage.app',
  );
}
