import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart';
import 'providers/auth_provider.dart' as app_auth;
import 'screens/auth/sign_in_screen.dart';
import 'screens/home/home_screen.dart';
import 'services/messaging_service.dart';
import 'providers/session_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load Spotify credentials (see .env.example).
  await dotenv.load(fileName: '.env');

  // Initialize Firebase using the config generated by `flutterfire configure`.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const VibzcheckApp());
}

class VibzcheckApp extends StatelessWidget {
  const VibzcheckApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
  providers: [
    ChangeNotifierProvider(create: (_) => app_auth.AuthProvider()),
    ChangeNotifierProvider(create: (_) => SessionProvider()),
  ],
      child: MaterialApp(
        title: 'Vibzcheck',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color(0xFF6C5CE7), // Vibzcheck purple
            brightness: Brightness.dark,
          ),
          useMaterial3: true,
        ),
        home: const AuthGate(),
      ),
    );
  }
}

/// AuthGate listens to Firebase Auth state and routes to the correct screen.
/// - Signed in  -> HomeScreen
/// - Signed out -> SignInScreen
/// This is a single source of truth: no screen ever manually checks auth state.
class AuthGate extends StatefulWidget {
  const AuthGate({super.key});

  @override
  State<AuthGate> createState() => _AuthGateState();
}

class _AuthGateState extends State<AuthGate> {
  final MessagingService _messaging = MessagingService();
  String? _initializedForUid;

  Future<void> _initMessagingIfNeeded(User? user) async {
    if (user == null) {
      _initializedForUid = null;
      return;
    }
    // Skip if we've already initialized for this user (auth stream can
    // emit the same user multiple times across rebuilds).
    if (_initializedForUid == user.uid) return;
    _initializedForUid = user.uid;
    try {
      await _messaging.initialize();
    } catch (e) {
      // Don't block the UI on FCM failures. Notifications are best-effort.
      // ignore: avoid_print
      print('[MessagingService] initialize failed: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        // Trigger messaging init for the freshly signed-in user. We don't
        // await — UI shouldn't block on permission prompts or token network.
        _initMessagingIfNeeded(snapshot.data);

        if (snapshot.hasData) {
          return const HomeScreen();
        }
        return const SignInScreen();
      },
    );
  }
}
